DataHunter/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('symptoms/', include('symptoms.urls')),
    path('gov-data/', include('gov_datas.urls')),
    path('accounts/', include('allauth.urls')),  # allauth URLs
]

# 在開發模式下提供靜態檔案
if settings.DEBUG:
    # 在開發模式下，Django 會自動尋找靜態檔案
    # 但我們還是明確加上以確保正確
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

RAGPilot/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('', include('crawlers.urls')),
    path('conversations/', include('conversations.urls')),
    path('sources/', include('sources.urls')),
    path('websites/', include('websites.urls')),  # websites URLs
    path('accounts/', include('allauth.urls')),  # allauth URLs
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')), name='favicon'),
]

# 在開發模式下提供靜態檔案
if settings.DEBUG:
    # 在開發模式下，Django 會自動尋找靜態檔案
    # 但我們還是明確加上以確保正確
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from .views import HomeView, CustomLoginView, CustomLogoutView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
] 

profiles/urls.py
from django.urls import path
from .views import ProfileView

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
] 

crawlers/models/symptom.py
from django.db import models
from django.db.models import QuerySet
from pgvector.django import VectorField, HnswIndex
from typing import Optional





class SymptomQuerySet(models.QuerySet):
    """Symptom 查詢集，包含自定義查詢方法"""
    
    def build_queryset(
        self,
        department: Optional[str] = None, 
        gender: Optional[str] = None, 
        question: Optional[str] = None
    ) -> 'SymptomQuerySet':
        """
        構建 Symptom 查詢集
        統一的查詢構建方法，支援多種過濾條件
        """
        from utils.search import hybrid_search_with_rerank
        
        queryset = self
        
        if department:
            queryset = queryset.filter(department__icontains=department)
        
        if gender:
            queryset = queryset.filter(gender=gender)
        
        if question:
            queryset = hybrid_search_with_rerank(
                queryset=queryset,
                vector_field_name="question_embeddings",
                text_field_name="question",
                original_question=question,
            )
        else:
            queryset = queryset.order_by("-question_time")
        
        return queryset


class SymptomManager(models.Manager):
    """Symptom 管理器"""
    
    def get_queryset(self):
        return SymptomQuerySet(self.model, using=self._db)
    
    def build_queryset(self, **kwargs):
        return self.get_queryset().build_queryset(**kwargs)


class Symptom(models.Model):
    id = models.AutoField(primary_key=True)

    subject_id = models.IntegerField()
    subject = models.CharField(max_length=255)
    department = models.CharField(max_length=255)

    symptom = models.CharField(max_length=255)
    question = models.TextField(db_index=True)
    answer = models.TextField()

    gender = models.CharField(max_length=10)

    question_time = models.DateTimeField(help_text="網站上的患者提問時間。")
    answer_time = models.DateTimeField(help_text="網站上的醫師回答時間。")

    question_embeddings = VectorField(
        dimensions=1536,
        help_text="基於 question 欄位並使用 OpenAI text-embedding-3-small 產生向量。"
    )

    # 使用自定義管理器
    objects = SymptomManager()

    class Meta:
        verbose_name = '衛福部-台灣e院-症狀'
        verbose_name_plural = '衛福部-台灣e院-症狀'
        indexes = [
            HnswIndex(
                name="crawlers_symp_q_emb_hnsw_idx",
                fields=["question_embeddings"],
                m=16,
                ef_construction=64,
                opclasses=["vector_l2_ops"],
            )
        ]

    def __str__(self):
        return str(self.id) 

home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UsernameAuthenticationForm(AuthenticationForm):
    """
    自定義登入表單，允許用戶使用 username 登入
    """
    username = forms.CharField(
        label='使用者名稱',
        widget=forms.TextInput(attrs={
            'class': 'input input-bordered w-full pl-10',
            'placeholder': '請輸入您的使用者名稱'
        })
    )
    
    password = forms.CharField(
        label='密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full pl-10',
            'placeholder': '請輸入密碼'
        })
    ) 

profiles/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserProfileForm(forms.ModelForm):
    """
    用戶個人資料編輯表單
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 將 username 和 email 欄位設為不可編輯
        if self.instance and self.instance.pk:
            self.fields['username'].disabled = True
            self.fields['username'].help_text = '使用者名稱不可更改，以確保系統穩定性'
            self.fields['email'].disabled = True
            self.fields['email'].help_text = 'Email 不可更改，以確保帳號安全性'
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username': '使用者名稱',
            'email': 'Email',
            'first_name': '名',
            'last_name': '姓',
        }
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'input input-bordered w-full bg-gray-100',
                'placeholder': '使用者名稱不可更改',
                'readonly': True
            }),
            'email': forms.EmailInput(attrs={
                'class': 'input input-bordered w-full bg-gray-100',
                'placeholder': 'Email 不可更改',
                'readonly': True
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'input input-bordered w-full',
                'placeholder': '請輸入名'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'input input-bordered w-full',
                'placeholder': '請輸入姓'
            }),
        }
    
    def clean_username(self):
        """
        確保 username 不會被更改
        """
        if self.instance and self.instance.pk:
            # 如果是編輯現有用戶，返回原始的 username
            return self.instance.username
        return self.cleaned_data.get('username')
    
    def clean_email(self):
        """
        確保 email 不會被更改
        """
        if self.instance and self.instance.pk:
            # 如果是編輯現有用戶，返回原始的 email
            return self.instance.email
        return self.cleaned_data.get('email')


class CustomPasswordChangeForm(PasswordChangeForm):
    """
    自定義密碼修改表單（適用於已有密碼的用戶）
    """
    old_password = forms.CharField(
        label='當前密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full',
            'placeholder': '請輸入當前密碼'
        })
    )
    new_password1 = forms.CharField(
        label='新密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full',
            'placeholder': '請輸入新密碼'
        })
    )
    new_password2 = forms.CharField(
        label='確認新密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full',
            'placeholder': '請再次輸入新密碼'
        })
    )


class CustomSetPasswordForm(SetPasswordForm):
    """
    自定義設定密碼表單（適用於沒有密碼的用戶，如 Google 登入用戶）
    """
    new_password1 = forms.CharField(
        label='設定密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full',
            'placeholder': '請設定您的登入密碼'
        }),
        help_text='設定密碼後，您可以使用 username + 密碼的方式登入'
    )
    new_password2 = forms.CharField(
        label='確認密碼',
        widget=forms.PasswordInput(attrs={
            'class': 'input input-bordered w-full',
            'placeholder': '請再次輸入密碼'
        })
    ) 

crawlers/views/gov_data.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.http import JsonResponse
from django.views import View
from django.conf import settings
from crawlers.models import Dataset, ASSOCIATED_CATEGORIES_DATABASE_NAME
from home.mixins import UserPlanContextMixin



@method_decorator(never_cache, name='dispatch')
class GovDataDatasetListView(LoginRequiredMixin, UserPlanContextMixin, ListView):
    model = Dataset
    template_name = 'gov_datas.html'
    context_object_name = 'datasets'
    paginate_by = 20
    login_url = '/login/'  # 未登入時重定向的 URL

    def get_queryset(self):
        category = self.request.GET.get('category')
        description = self.request.GET.get('description')
        name = self.request.GET.get('name')
        upload_start = self.request.GET.get('upload_start')
        upload_end = self.request.GET.get('upload_end')
        update_start = self.request.GET.get('update_start')
        update_end = self.request.GET.get('update_end')
        
        queryset = Dataset.objects.build_queryset(
            category=category,
            description=description,
            name=name,
            upload_start=upload_start,
            upload_end=upload_end,
            update_start=update_start,
            update_end=update_end
        )
        
        # 預載入檔案關聯以提高效能
        return queryset.prefetch_related('file_set')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['categories'] = ASSOCIATED_CATEGORIES_DATABASE_NAME.keys()
        
        # 保存當前過濾條件
        context['category'] = self.request.GET.get('category', '')
        context['description'] = self.request.GET.get('description', '')
        context['name'] = self.request.GET.get('name', '')
        context['upload_start'] = self.request.GET.get('upload_start', '')
        context['upload_end'] = self.request.GET.get('upload_end', '')
        context['update_start'] = self.request.GET.get('update_start', '')
        context['update_end'] = self.request.GET.get('update_end', '')
        context['request_path'] = self.request.path
        
        return context

class GovDataSuggestView(LoginRequiredMixin, View):
    
    def get(self, request):
        """使用重構後的工具生成政府資料建議問題"""
        from utils.question_suggestions import generate_gov_data_suggestions
        
        return generate_gov_data_suggestions()
        

crawlers/views/symptom.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.http import JsonResponse
from django.views import View
from crawlers.models import Symptom
from home.mixins import UserPlanContextMixin


@method_decorator(never_cache, name='dispatch')
class SymptomListView(LoginRequiredMixin, UserPlanContextMixin, ListView):
    template_name = 'symptoms.html'
    context_object_name = 'symptoms'
    queryset = Symptom.objects.all()
    paginate_by = 10
    login_url = '/login/'

    def get_queryset(self):
        department = self.request.GET.get('department')
        gender = self.request.GET.get('gender')
        question = self.request.GET.get('question')
        
        return Symptom.objects.build_queryset(
            department=department, 
            gender=gender, 
            question=question
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request_path'] = self.request.path
        context['department'] = self.request.GET.get('department', '')
        context['gender'] = self.request.GET.get('gender', '')
        context['question'] = self.request.GET.get('question', '')
        context['departments'] = Symptom.objects.values_list('department', flat=True).distinct().order_by('department')
        context['genders'] = Symptom.objects.values_list('gender', flat=True).distinct().order_by('gender')
          
        return context 


class SymptomSuggestView(LoginRequiredMixin, View):
    
    def get(self, request):
        """使用重構後的工具生成症狀建議問題"""
        from utils.question_suggestions import generate_symptom_suggestions
        
        return generate_symptom_suggestions()
        
        

home/views.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth import logout, get_user_model
from django.http import HttpResponseRedirect
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.conf import settings
from .forms import UsernameAuthenticationForm
from .mixins import UserPlanContextMixin

User = get_user_model()

@method_decorator(never_cache, name='dispatch')
class HomeView(LoginRequiredMixin, UserPlanContextMixin, TemplateView):
    template_name = 'home.html'
    login_url = '/login/'  # 未登入時重定向的 URL

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request_path'] = self.request.path
        return context

class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = UsernameAuthenticationForm  # 使用自定義表單
    success_url = reverse_lazy('home')  # 登入成功後重定向到首頁
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')  # 如果已登入，直接跳轉到首頁
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # 添加用戶數量統計信息
        total_users = User.objects.count()
        max_users_limit = getattr(settings, 'MAX_USERS_LIMIT', 200)
        remaining_slots = max_users_limit - total_users
        usage_percentage = (total_users / max_users_limit) * 100 if max_users_limit > 0 else 0
        
        # 決定是否顯示狀態提示
        show_status = usage_percentage >= 80  # 使用率達到 80% 時開始顯示
        
        if show_status:
            if usage_percentage >= 100:
                status_class = 'alert-error'
                status_icon = '🚫'
                status_title = '註冊已暫停'
                status_message = f'系統已達用戶上限（{max_users_limit}人），暫時無法接受新用戶註冊。如需註冊請聯繫管理員。'
            elif usage_percentage >= 95:
                status_class = 'alert-warning'
                status_icon = '⚠️'
                status_title = '名額緊張'
                status_message = f'系統接近用戶上限，僅剩 {remaining_slots} 個註冊名額。'
            elif usage_percentage >= 90:
                status_class = 'alert-warning'
                status_icon = '📢'
                status_title = '名額有限'
                status_message = f'系統用戶數量較多，剩餘 {remaining_slots} 個註冊名額。'
            else:  # >= 80%
                status_class = 'alert-info'
                status_icon = 'ℹ️'
                status_title = '系統提示'
                status_message = f'目前系統用戶較多，剩餘 {remaining_slots} 個註冊名額。'
        
        context.update({
            'user_limit_status': {
                'show_status': show_status,
                'status_class': status_class if show_status else '',
                'status_icon': status_icon if show_status else '',
                'status_title': status_title if show_status else '',
                'status_message': status_message if show_status else '',
                'total_users': total_users,
                'max_users_limit': max_users_limit,
                'remaining_slots': remaining_slots,
                'usage_percentage': round(usage_percentage, 1),
            }
        })
        
        return context

class CustomLogoutView(View):
    """
    自定義登出視圖，確保正確清除會話並重定向到登入頁
    """
    def get(self, request):
        return self.logout_user(request)
    
    def post(self, request):
        return self.logout_user(request)
    
    def logout_user(self, request):
        # 清除會話
        logout(request)
        
        # 創建重定向響應
        response = HttpResponseRedirect('/login/')
        
        # 添加緩存控制標頭，防止瀏覽器緩存
        response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        response['Pragma'] = 'no-cache'
        response['Expires'] = '0'
        
        return response

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-TW" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>數據領航員 RAGPilot</title>
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}?v=2">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}?v=2">
    <meta name="msapplication-TileImage" content="{% static 'favicon.ico' %}?v=2">
    <meta name="theme-color" content="#ffffff">
    
    <!-- Tailwind CSS with DaisyUI (CDN 版本) -->
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    
    <!-- 額外的 CSS -->
    {% block extra_css %}{% endblock %}
</head>
<body class="{% block body_class %}min-h-screen bg-gray-50 flex flex-col{% endblock %}">
    
    <!-- 主要內容區域 -->
    {% block content %}{% endblock %}
    
    <!-- 底部連結區域 - 可選擇性顯示 -->
    {% block footer %}{% endblock %}
    
    <!-- 使用條款彈出視窗 -->
    {% include '_terms_modal.html' %}
    
    <!-- 顯示 Django messages -->
    {% if messages %}
        <div id="django-messages" class="fixed top-4 right-4 z-50 space-y-2">
            {% for message in messages %}
                <div class="alert 
                    {% if message.tags == 'error' %}alert-error{% endif %}
                    {% if message.tags == 'warning' %}alert-warning{% endif %}
                    {% if message.tags == 'success' %}alert-success{% endif %}
                    {% if message.tags == 'info' %}alert-info{% endif %}
                    shadow-lg" 
                    data-message="{{ message|escapejs }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        
        <script>
            // 過濾登入成功訊息
            document.addEventListener('DOMContentLoaded', function() {
                const messageElements = document.querySelectorAll('#django-messages .alert');
                const loginKeywords = ['登入成功', 'logged in', 'successfully signed in', 'nickchen'];
                
                messageElements.forEach(function(element) {
                    const messageText = element.textContent || element.innerText;
                    const shouldHide = loginKeywords.some(keyword => 
                        messageText.toLowerCase().includes(keyword.toLowerCase())
                    );
                    
                    if (shouldHide) {
                        element.style.display = 'none';
                    }
                });
            });
        </script>
    {% endif %}
    
    <!-- 基礎 JavaScript -->
    <script>
        // 通用的表單提交載入狀態
        function setupFormLoadingStates() {
            document.querySelectorAll('form').forEach(form => {
                // 跳過使用 AJAX 的過濾器表單
                if (form.id === 'filter-form') {
                    return;
                }
                
                form.addEventListener('submit', function(e) {
                    const submitBtn = this.querySelector('button[type="submit"]');
                    if (submitBtn) {
                        submitBtn.classList.add('loading');
                        submitBtn.disabled = true;
                    }
                });
            });
        }

        // 通用的提示訊息自動隱藏
        function setupAutoHideAlerts() {
            setTimeout(() => {
                const successAlerts = document.querySelectorAll('.alert-success');
                successAlerts.forEach(alert => {
                    alert.style.transition = 'opacity 0.5s';
                    alert.style.opacity = '0';
                    setTimeout(() => alert.remove(), 500);
                });
            }, 3000);
        }

        // 頁面載入完成後執行通用初始化
        document.addEventListener('DOMContentLoaded', function() {
            setupFormLoadingStates();
            setupAutoHideAlerts();
        });
    </script>
    
    <!-- 頁面特定的 JavaScript -->
    {% block extra_js %}{% endblock %}
</body>
</html> 

templates/symptoms.html
{% extends 'home.html' %}

{% block chat_widget %}
    {% include 'chat_widget.html' %}
{% endblock %}

{% block source-description %}
{% endblock %}

{% block filter_section %}
    <form id="filter-form" method="get" action="{% url 'symptom_list' %}" class="bg-gray-50 p-4 rounded-lg shadow-inner mb-4">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
                <label for="department-select" class="block font-semibold mb-1">科別：</label>
                <select id="department-select" name="department" class="select select-bordered w-full">
                    <option value="">所有科別</option>
                    {% for dept in departments %}
                        <option value="{{ dept }}" {% if dept == department %}selected{% endif %}>{{ dept }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="gender-select" class="block font-semibold mb-1">性別：</label>
                <select id="gender-select" name="gender" class="select select-bordered w-full">
                    <option value="">所有性別</option>
                    {% for gender_option in genders %}
                        <option value="{{ gender_option }}" {% if gender_option == gender %}selected{% endif %}>{{ gender_option }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="question-input" class="block font-semibold mb-1">症狀描述：</label>
                <input id="question-input" name="question" type="text" placeholder="輸入症狀關鍵字..." 
                       value="{{ question }}" class="input input-bordered w-full">
            </div>
        </div>
        <div class="flex justify-end mt-4 space-x-2">
            <button type="button" id="clear-btn" class="btn btn-ghost">清除</button>
            <button type="submit" class="btn btn-primary">搜尋</button>
        </div>
    </form>
{% endblock %}

{% block data-table %}
    <div class="data-table h-full overflow-y-auto pr-2 space-y-4">
        {% if object_list %}
            {% for data in object_list %}
                <div class="card shadow-md bg-white p-4 border border-gray-200">
                    <div class="flex justify-between items-start">
                        <div class="flex-1 space-y-2 text-sm text-gray-800">
                            <div><span class="font-semibold">科別：</span>{{ data.department }}</div>
                            <div><span class="font-semibold">性別：</span>{{ data.gender }}</div>
                            <div><span class="font-semibold">主訴：</span>{{ data.symptom }}</div>
                            <div>
                                <span class="font-semibold">症狀描述：</span>
                                {% if data.question|length > 100 %}
                                    <span id="question-preview-{{ data.id }}">{{ data.question|slice:":100" }}...</span>
                                    <span id="question-full-{{ data.id }}" style="display: none;">{{ data.question }}</span>
                                    <button data-id="{{ data.id }}" data-field="question"
                                            class="btn btn-xs btn-outline btn-info ml-2 toggle-button">展開
                                    </button>
                                {% else %}
                                    {{ data.question }}
                                {% endif %}
                            </div>
                            <div>
                                <span class="font-semibold">醫師回覆：</span>
                                {% if data.answer|length > 100 %}
                                    <span id="answer-preview-{{ data.id }}">{{ data.answer|slice:":100" }}...</span>
                                    <span id="answer-full-{{ data.id }}" style="display: none;">{{ data.answer }}</span>
                                    <button data-id="{{ data.id }}" data-field="answer"
                                            class="btn btn-xs btn-outline btn-info ml-2 toggle-button">展開
                                    </button>
                                {% else %}
                                    {{ data.answer }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="ml-4 flex-shrink-0">
                            <button class="btn btn-sm btn-outline btn-success add-reference-btn" 
                                    data-id="{{ data.id }}"
                                    data-department="{{ data.department }}"
                                    data-gender="{{ data.gender }}"
                                    data-symptom="{{ data.symptom }}"
                                    data-question="{{ data.question }}"
                                    data-answer="{{ data.answer }}">
                                <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
                                </svg>
                                加入對話
                            </button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="card shadow-md bg-white p-4 border border-gray-200">
                <div class="space-y-2 text-sm text-gray-800">
                    <div class="text-center text-gray-500">沒有找到符合條件的資料</div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}